
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
      - name: Run pytest
        working-directory: ./EPAM_final
        run: |
            conda install pytest
            py.test tests
