name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        working-directory: ./EPAM_final
        run: |
          pip install pytest geopandas aiohttp bs4
          py.test tests
