name: CI

on: push

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - uses: actions/checkout@v1
      - name: Update Conda environment with "requirements.yml"
        uses: matthewrmshin/conda-action@v1
        with:
          args: conda env update -f ./EPAM_final/requirements.txt
      - name: Run "pytest" with the Conda environment
        uses: matthewrmshin/conda-action@v1
        with:
          args: pytest
      - name: test
        working-directory: ./EPAM_final
        run: |
            py.test tests
